#ifndef TENSOR_READER_H
#define TENSOR_READER_H

/* Generated by flatcc 0.6.1 FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#ifndef SCHEMA_READER_H
#include "Schema_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension "bin"
#endif


typedef const struct org_apache_arrow_flatbuf_TensorDim_table *org_apache_arrow_flatbuf_TensorDim_table_t;
typedef struct org_apache_arrow_flatbuf_TensorDim_table *org_apache_arrow_flatbuf_TensorDim_mutable_table_t;
typedef const flatbuffers_uoffset_t *org_apache_arrow_flatbuf_TensorDim_vec_t;
typedef flatbuffers_uoffset_t *org_apache_arrow_flatbuf_TensorDim_mutable_vec_t;
typedef const struct org_apache_arrow_flatbuf_Tensor_table *org_apache_arrow_flatbuf_Tensor_table_t;
typedef struct org_apache_arrow_flatbuf_Tensor_table *org_apache_arrow_flatbuf_Tensor_mutable_table_t;
typedef const flatbuffers_uoffset_t *org_apache_arrow_flatbuf_Tensor_vec_t;
typedef flatbuffers_uoffset_t *org_apache_arrow_flatbuf_Tensor_mutable_vec_t;
#ifndef org_apache_arrow_flatbuf_TensorDim_file_identifier
#define org_apache_arrow_flatbuf_TensorDim_file_identifier 0
#endif
/* deprecated, use org_apache_arrow_flatbuf_TensorDim_file_identifier */
#ifndef org_apache_arrow_flatbuf_TensorDim_identifier
#define org_apache_arrow_flatbuf_TensorDim_identifier 0
#endif
#define org_apache_arrow_flatbuf_TensorDim_type_hash ((flatbuffers_thash_t)0xbc6d7b25)
#define org_apache_arrow_flatbuf_TensorDim_type_identifier "\x25\x7b\x6d\xbc"
#ifndef org_apache_arrow_flatbuf_TensorDim_file_extension
#define org_apache_arrow_flatbuf_TensorDim_file_extension "bin"
#endif
#ifndef org_apache_arrow_flatbuf_Tensor_file_identifier
#define org_apache_arrow_flatbuf_Tensor_file_identifier 0
#endif
/* deprecated, use org_apache_arrow_flatbuf_Tensor_file_identifier */
#ifndef org_apache_arrow_flatbuf_Tensor_identifier
#define org_apache_arrow_flatbuf_Tensor_identifier 0
#endif
#define org_apache_arrow_flatbuf_Tensor_type_hash ((flatbuffers_thash_t)0x1764df19)
#define org_apache_arrow_flatbuf_Tensor_type_identifier "\x19\xdf\x64\x17"
#ifndef org_apache_arrow_flatbuf_Tensor_file_extension
#define org_apache_arrow_flatbuf_Tensor_file_extension "bin"
#endif



/**  ----------------------------------------------------------------------
 *  Data structures for dense tensors
 *  Shape data for a single axis in a tensor */
struct org_apache_arrow_flatbuf_TensorDim_table { uint8_t unused__; };

static inline size_t org_apache_arrow_flatbuf_TensorDim_vec_len(org_apache_arrow_flatbuf_TensorDim_vec_t vec)
__flatbuffers_vec_len(vec)
static inline org_apache_arrow_flatbuf_TensorDim_table_t org_apache_arrow_flatbuf_TensorDim_vec_at(org_apache_arrow_flatbuf_TensorDim_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(org_apache_arrow_flatbuf_TensorDim_table_t, vec, i, 0)
__flatbuffers_table_as_root(org_apache_arrow_flatbuf_TensorDim)

/**  Length of dimension */
__flatbuffers_define_scalar_field(0, org_apache_arrow_flatbuf_TensorDim, size, flatbuffers_int64, int64_t, INT64_C(0))
/**  Name of the dimension, optional */
__flatbuffers_define_string_field(1, org_apache_arrow_flatbuf_TensorDim, name, 0)

struct org_apache_arrow_flatbuf_Tensor_table { uint8_t unused__; };

static inline size_t org_apache_arrow_flatbuf_Tensor_vec_len(org_apache_arrow_flatbuf_Tensor_vec_t vec)
__flatbuffers_vec_len(vec)
static inline org_apache_arrow_flatbuf_Tensor_table_t org_apache_arrow_flatbuf_Tensor_vec_at(org_apache_arrow_flatbuf_Tensor_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(org_apache_arrow_flatbuf_Tensor_table_t, vec, i, 0)
__flatbuffers_table_as_root(org_apache_arrow_flatbuf_Tensor)

/**  The type of data contained in a value cell. Currently only fixed-width
 *  value types are supported, no strings or nested types */
__flatbuffers_define_union_field(flatbuffers_, 1, org_apache_arrow_flatbuf_Tensor, type, org_apache_arrow_flatbuf_Type, 1)
/**  The dimensions of the tensor, optionally named */
__flatbuffers_define_vector_field(2, org_apache_arrow_flatbuf_Tensor, shape, org_apache_arrow_flatbuf_TensorDim_vec_t, 1)
/**  Non-negative byte offsets to advance one value cell along each dimension
 *  If omitted, default to row-major order (C-like). */
__flatbuffers_define_vector_field(3, org_apache_arrow_flatbuf_Tensor, strides, flatbuffers_int64_vec_t, 0)
/**  The location and size of the tensor's data */
__flatbuffers_define_struct_field(4, org_apache_arrow_flatbuf_Tensor, data, org_apache_arrow_flatbuf_Buffer_struct_t, 1)


#include "flatcc/flatcc_epilogue.h"
#endif /* TENSOR_READER_H */
